import {expect, test} from "@playwright/test"
import {composeBox, openCompose} from "./helpers"
import {caretSnap, findText, selectAllKey, wordKey} from "./caret"

test("arrow keys walk a plain paragraph by unit", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("ab")
    let afterType = await caretSnap(page)
    expect(afterType.empty).toBe(true)
    expect(afterType.block).toBe("Paragraph")
    expect(afterType.blockText).toBe("ab")
    expect(afterType.head).toBe(afterType.from)
    let end = afterType.head
    await page.keyboard.press("ArrowLeft")
    let mid = await caretSnap(page)
    expect(mid.head).toBe(end - 1)
    expect(mid.blockText).toBe("ab")
    await page.keyboard.press("ArrowLeft")
    let start = await caretSnap(page)
    expect(start.head).toBe(end - 2)
    await page.keyboard.press("ArrowLeft")
    let stuck = await caretSnap(page)
    expect(stuck.head).toBe(start.head)
    await page.keyboard.press("ArrowRight")
    await page.keyboard.press("ArrowRight")
    let back = await caretSnap(page)
    expect(back.head).toBe(end)
    expect(back.cursorClass).toMatch(/arrisa-cursor-v/)
})

test("shift-arrow extends and a bare arrow collapses to the bound", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("abcd")
    await page.keyboard.press("ArrowLeft")
    await page.keyboard.press("ArrowLeft")
    await page.keyboard.press("Shift+ArrowRight")
    await page.keyboard.press("Shift+ArrowRight")
    let range = await caretSnap(page)
    expect(range.empty).toBe(false)
    expect(range.to - range.from).toBe(2)
    expect(range.head).toBe(range.to)
    await page.keyboard.press("ArrowRight")
    let collapsed = await caretSnap(page)
    expect(collapsed.empty).toBe(true)
    expect(collapsed.head).toBe(range.to)
    await page.keyboard.press("Shift+ArrowLeft")
    await page.keyboard.press("Shift+ArrowLeft")
    let leftRange = await caretSnap(page)
    expect(leftRange.empty).toBe(false)
    await page.keyboard.press("ArrowLeft")
    let leftBound = await caretSnap(page)
    expect(leftBound.empty).toBe(true)
    expect(leftBound.head).toBe(leftRange.from)
})

test("word motion skips to word edges", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("hi there")
    let there = await findText(page, "there")
    await page.keyboard.press(wordKey("left"))
    let atThere = await caretSnap(page)
    expect(atThere.head).toBe(there.from)
    await page.keyboard.press(wordKey("left"))
    let atHi = await caretSnap(page)
    let hi = await findText(page, "hi")
    expect(atHi.head).toBe(hi.from)
    await page.keyboard.press(wordKey("right"))
    let afterHi = await caretSnap(page)
    expect(afterHi.head).toBe(hi.to)
    await page.keyboard.press(wordKey("right", true))
    let wordRange = await caretSnap(page)
    expect(wordRange.empty).toBe(false)
    expect(wordRange.from).toBe(hi.to)
    expect(wordRange.to).toBe(there.to)
})

test("home and end move to the visual line side", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("hello")
    await page.keyboard.press("Shift+Enter")
    await page.keyboard.type("world")
    let world = await findText(page, "world")
    let hello = await findText(page, "hello")
    await page.keyboard.press("Home")
    let lineStart = await caretSnap(page)
    expect(lineStart.head).toBe(world.from)
    expect(lineStart.blockText).toContain("hello")
    expect(lineStart.blockText).toContain("world")
    await page.keyboard.press("End")
    let lineEnd = await caretSnap(page)
    expect(lineEnd.head).toBe(world.to)
    await page.keyboard.press("Shift+Home")
    let lineSel = await caretSnap(page)
    expect(lineSel.empty).toBe(false)
    expect(lineSel.from).toBe(world.from)
    expect(lineSel.to).toBe(world.to)
    await page.keyboard.press("ArrowUp")
    let upper = await caretSnap(page)
    expect(upper.head).toBeGreaterThanOrEqual(hello.from)
    expect(upper.head).toBeLessThanOrEqual(hello.to)
    await page.keyboard.press("ArrowDown")
    let lower = await caretSnap(page)
    expect(lower.head).toBeGreaterThanOrEqual(world.from)
    expect(lower.head).toBeLessThanOrEqual(world.to)
})

test("two paragraphs: enter splits, arrows cross the boundary", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("hello")
    await page.keyboard.press("Enter")
    await page.keyboard.type("world")
    let two = await caretSnap(page)
    expect(two.names).toEqual(["Paragraph", "Paragraph"])
    expect(two.blockText).toBe("world")
    await page.keyboard.press("ArrowUp")
    let upper = await caretSnap(page)
    expect(upper.blockText).toBe("hello")
    await page.keyboard.press("End")
    await page.keyboard.press("ArrowRight")
    let lower = await caretSnap(page)
    expect(lower.blockText).toBe("world")
    await page.keyboard.press("Home")
    await page.keyboard.press("ArrowLeft")
    let back = await caretSnap(page)
    expect(back.blockText).toBe("hello")
})

test("mod-home and mod-end move to the document sides", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("hello")
    await page.keyboard.press("Enter")
    await page.keyboard.type("world")
    let hello = await findText(page, "hello")
    let world = await findText(page, "world")
    await page.keyboard.press("ControlOrMeta+Home")
    let start = await caretSnap(page)
    expect(start.head).toBe(hello.from)
    expect(start.blockText).toBe("hello")
    await page.keyboard.press("ControlOrMeta+End")
    let end = await caretSnap(page)
    expect(end.head).toBe(world.to)
    expect(end.blockText).toBe("world")
    await page.keyboard.press("Shift+ControlOrMeta+Home")
    let all = await caretSnap(page)
    expect(all.empty).toBe(false)
    expect(all.from).toBe(hello.from)
    expect(all.to).toBe(world.to)
})

test("select-all and escape collapse the range at head", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("hello")
    await page.keyboard.press(selectAllKey())
    let selected = await caretSnap(page)
    expect(selected.empty).toBe(false)
    expect(selected.from).toBe(0)
    expect(selected.to).toBeGreaterThan(selected.from)
    let head = selected.head
    await page.keyboard.press("Escape")
    let collapsed = await caretSnap(page)
    expect(collapsed.empty).toBe(true)
    expect(collapsed.head).toBe(head)
})
