import {expect, test} from "@playwright/test"
import {composeBox, openCompose} from "./helpers"
import {caretSnap, clickDocPos, findText, typeFence, waitFrames, wordKey} from "./caret"

test("arrows walk inside a code block and stay in CodeBlock", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await typeFence(page, "py")
    await page.keyboard.type("ab")
    let end = await caretSnap(page)
    expect(end.block).toBe("CodeBlock")
    expect(end.blockText).toBe("ab")
    expect(end.names).toEqual(["CodeBlock"])
    await page.keyboard.press("ArrowLeft")
    let mid = await caretSnap(page)
    expect(mid.block).toBe("CodeBlock")
    expect(mid.head).toBe(end.head - 1)
    await page.keyboard.press("ArrowLeft")
    let start = await caretSnap(page)
    expect(start.block).toBe("CodeBlock")
    expect(start.head).toBe(end.head - 2)
    await page.keyboard.press("ArrowRight")
    await page.keyboard.press("ArrowRight")
    let back = await caretSnap(page)
    expect(back.block).toBe("CodeBlock")
    expect(back.head).toBe(end.head)
    expect(back.cursorClass).toMatch(/arrisa-cursor-v/)
})

test("arrow right at the end of a lone code block inserts a paragraph", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await typeFence(page, "py")
    await page.keyboard.type("ab")
    await page.keyboard.press("ArrowRight")
    let after = await caretSnap(page)
    expect(after.names).toEqual(["CodeBlock", "Paragraph"])
    expect(after.block).toBe("Paragraph")
    expect(after.blockText).toBe("")
    expect(after.cursorClass).toMatch(/arrisa-cursor-v/)
    await page.keyboard.press("ArrowLeft")
    let back = await caretSnap(page)
    expect(back.block).toBe("CodeBlock")
    expect(back.blockText).toBe("ab")
})

test("shift-arrow right at the end of a code block does not insert a paragraph", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await typeFence(page, "py")
    await page.keyboard.type("ab")
    let end = await caretSnap(page)
    await page.keyboard.press("Shift+ArrowRight")
    let snap = await caretSnap(page)
    expect(snap.names).toEqual(["CodeBlock"])
    expect(snap.block).toBe("CodeBlock")
    expect(snap.empty).toBe(true)
    expect(snap.head).toBe(end.head)
})

test("arrow right from a code block enters a following paragraph", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("hello")
    await page.keyboard.press("Enter")
    await typeFence(page, "py")
    await page.keyboard.type("ab")
    await page.keyboard.press("ArrowRight")
    await page.keyboard.type("bye")
    let mixed = await caretSnap(page)
    expect(mixed.names).toEqual(["Paragraph", "CodeBlock", "Paragraph"])
    expect(mixed.blockText).toBe("bye")
    await page.keyboard.press("Home")
    await page.keyboard.press("ArrowLeft")
    let inCode = await caretSnap(page)
    expect(inCode.block).toBe("CodeBlock")
    expect(inCode.blockText).toBe("ab")
    await page.keyboard.press("ArrowRight")
    let inBye = await caretSnap(page)
    expect(inBye.block).toBe("Paragraph")
    expect(inBye.blockText).toBe("bye")
    await page.keyboard.press("ControlOrMeta+Home")
    await page.keyboard.press("End")
    await page.keyboard.press("ArrowRight")
    let fromHello = await caretSnap(page)
    expect(fromHello.block).toBe("CodeBlock")
    expect(fromHello.blockText).toBe("ab")
})

test("arrow right at the end of a code block enters the next code block", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await typeFence(page, "py")
    await page.keyboard.type("ab")
    await page.keyboard.press("ArrowRight")
    await typeFence(page, "ts")
    await page.keyboard.type("cd")
    let two = await caretSnap(page)
    expect(two.names).toEqual(["CodeBlock", "CodeBlock"])
    expect(two.blockText).toBe("cd")
    await page.keyboard.press("Home")
    await page.keyboard.press("ArrowLeft")
    let first = await caretSnap(page)
    expect(first.block).toBe("CodeBlock")
    expect(first.blockText).toBe("ab")
    await page.keyboard.press("ArrowRight")
    let second = await caretSnap(page)
    expect(second.block).toBe("CodeBlock")
    expect(second.blockText).toBe("cd")
})

test("shift-enter lines in a code block: up and down keep CodeBlock", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await typeFence(page, "py")
    await page.keyboard.type("ab")
    await page.keyboard.press("Shift+Enter")
    await page.keyboard.type("cd")
    let lower = await caretSnap(page)
    expect(lower.block).toBe("CodeBlock")
    expect(lower.blockText).toMatch(/ab/)
    expect(lower.blockText).toMatch(/cd/)
    expect(lower.names).toEqual(["CodeBlock"])
    let cd = await findText(page, "cd")
    let ab = await findText(page, "ab")
    await page.keyboard.press("ArrowUp")
    let upper = await caretSnap(page)
    expect(upper.block).toBe("CodeBlock")
    expect(upper.head).toBeGreaterThanOrEqual(ab.from)
    expect(upper.head).toBeLessThanOrEqual(ab.to)
    await page.keyboard.press("ArrowDown")
    let back = await caretSnap(page)
    expect(back.block).toBe("CodeBlock")
    expect(back.head).toBeGreaterThanOrEqual(cd.from)
    expect(back.head).toBeLessThanOrEqual(cd.to)
    await page.keyboard.press("Home")
    let lineStart = await caretSnap(page)
    expect(lineStart.head).toBe(cd.from)
    await page.keyboard.press("End")
    let lineEnd = await caretSnap(page)
    expect(lineEnd.head).toBe(cd.to)
})

test("arrow down from a paragraph enters the code block below", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await page.keyboard.type("hello")
    await page.keyboard.press("Enter")
    await typeFence(page, "py")
    await page.keyboard.type("print")
    await page.keyboard.press("ControlOrMeta+Home")
    let top = await caretSnap(page)
    expect(top.block).toBe("Paragraph")
    await page.keyboard.press("ArrowDown")
    let inCode = await caretSnap(page)
    expect(inCode.block).toBe("CodeBlock")
    expect(inCode.blockText).toBe("print")
    await page.keyboard.press("ArrowUp")
    let back = await caretSnap(page)
    expect(back.block).toBe("Paragraph")
    expect(back.blockText).toBe("hello")
})

test("arrow down from a code block enters the paragraph below", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await typeFence(page, "py")
    await page.keyboard.type("ab")
    await page.keyboard.press("ArrowRight")
    await page.keyboard.type("bye")
    let ab = await findText(page, "ab")
    await clickDocPos(page, ab.from, 1)
    let inCode = await caretSnap(page)
    expect(inCode.block).toBe("CodeBlock")
    expect(inCode.blockText).toBe("ab")
    await page.keyboard.press("ArrowDown")
    let below = await caretSnap(page)
    expect(below.block).toBe("Paragraph")
    expect(below.blockText).toBe("bye")
})

test("word motion inside code skips identifiers", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await typeFence(page, "py")
    await page.keyboard.type("print value")
    let value = await findText(page, "value")
    await page.keyboard.press(wordKey("left"))
    let atValue = await caretSnap(page)
    expect(atValue.block).toBe("CodeBlock")
    expect(atValue.head).toBe(value.from)
    await page.keyboard.press(wordKey("right"))
    let after = await caretSnap(page)
    expect(after.head).toBe(value.to)
    expect(after.block).toBe("CodeBlock")
})

test("caret in an empty code block is vertical and typing stays inside", async ({page}) => {
    await openCompose(page)
    await composeBox(page).click()
    await typeFence(page, "py")
    await waitFrames(page)
    let empty = await caretSnap(page)
    expect(empty.block).toBe("CodeBlock")
    expect(empty.blockText).toBe("")
    expect(empty.cursorClass).toMatch(/arrisa-cursor-v/)
    expect(empty.cursorClass).not.toMatch(/arrisa-cursor-h/)
    await page.keyboard.type("x")
    let typed = await caretSnap(page)
    expect(typed.block).toBe("CodeBlock")
    expect(typed.blockText).toBe("x")
})
